### ISSUE TITLE
歌词栏有闪烁

### ISSUE THREAD

**Issue by Cyberczy** [KairuiLiu/polybar-yesplaymusic-lyrics#1]
内容为(node:55044) [DEP0040] DeprecationWarning: The punycode mode is deprecated. Please use a userland alternative instead.
请问该如何解决

**Comment by Cyberczy** [comment]
> 内容为(node:55044) [DEP0040] DeprecationWarning: The punycode mode is deprecated. Please use a userland alternative instead. 请问该如何解决

已通过降级nodejs解决

**Comment by GarytheNoob** [comment]
另外一个解决方案：
在`lyric/lyric.bash`文件开头加入
```bash
export NODE_OPTIONS="--no-deprecation"
```

**Comment by Cyberczy** [comment]
> 另外一个解决方案： 在`lyric/lyric.bash`文件开头加入
> 
> ```shell
> export NODE_OPTIONS="--no-deprecation"
> ```

我现在也是这个解决方式hh

**Comment by Cyberczy** [comment]
> > 另外一个解决方案： 在`lyric/lyric.bash`文件开头加入
> > ```shell
> > export NODE_OPTIONS="--no-deprecation"
> > ```
> 
> 我现在也是这个解决方式hh

![image](https://github.com/KairuiLiu/polybar-yesplaymusic-lyrics/assets/109653523/9de5c1a0-18e4-4ea7-baeb-8b5d341c8ce8)
